### ISSUE TITLE
Building with xcaddy fails

### ISSUE THREAD

**Issue by mr-karan** [caddy-dns/cloudflare#11]
I tried to build `caddy` with this plugin using `xcaddy` but it failed.

**Command used**: 
```
xcaddy build  --with github.com/caddy-dns/cloudflare
```

**Output:**

```
2020/08/08 15:21:00 [INFO] Temporary folder: /tmp/buildenv_2020-08-08-1521.391743880
2020/08/08 15:21:00 [INFO] Writing main module: /tmp/buildenv_2020-08-08-1521.391743880/main.go
2020/08/08 15:21:00 [INFO] Initializing Go module
2020/08/08 15:21:00 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
go: creating new go.mod: module caddy
2020/08/08 15:21:00 [INFO] Pinning versions
2020/08/08 15:21:00 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.1.1 
go: downloading github.com/caddyserver/caddy/v2 v2.1.1
go: downloading go.uber.org/zap v1.15.0
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/caddyserver/certmagic v0.11.2
go: downloading go.uber.org/atomic v1.6.0
go: downloading go.uber.org/multierr v1.5.0
go: downloading github.com/go-acme/lego/v3 v3.7.0
go: downloading github.com/klauspost/cpuid v1.3.0
go: downloading golang.org/x/sys v0.0.0-20200413165638-669c56c373c4
go: downloading gopkg.in/square/go-jose.v2 v2.4.0
go: downloading github.com/cenkalti/backoff/v4 v4.0.0
go: downloading github.com/miekg/dns v1.1.27
go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
go: downloading golang.org/x/text v0.3.2
2020/08/08 15:21:34 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddy-dns/cloudflare 
go: downloading github.com/caddy-dns/cloudflare v0.0.0-20200807233547-c4ab2c801158
go: github.com/caddy-dns/cloudflare upgrade => v0.0.0-20200807233547-c4ab2c801158
go: downloading github.com/caddyserver/caddy/v2 v2.1.2-0.20200807181229-65a09524c392
go: downloading github.com/libdns/cloudflare v0.0.0-20200528144945-97886e7873b1
go: downloading github.com/libdns/libdns v0.0.0-20200501023120-186724ffc821
go: downloading golang.org/x/crypto v0.0.0-20200728195943-123391ffb6de
go: downloading github.com/caddyserver/certmagic v0.11.3-0.20200730200704-7d9dfc3fe638
go: downloading github.com/mholt/acmez v0.1.0
go: downloading github.com/miekg/dns v1.1.30
go: downloading golang.org/x/net v0.0.0-20200707034311-ab3426394381
2020/08/08 15:21:41 [INFO] Build environment ready
2020/08/08 15:21:41 [INFO] Building Caddy
2020/08/08 15:21:41 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /build/caddy -ldflags -w -s -trimpath 
go: downloading github.com/smallstep/certificates v0.15.0-rc.1.0.20200506212953-e855707dc274
go: downloading github.com/klauspost/compress v1.10.10
go: downloading github.com/google/cel-go v0.5.1
go: downloading google.golang.org/genproto v0.0.0-20200806141610-86f49bd18e98
go: downloading github.com/dustin/go-humanize v1.0.1-0.20200219035652-afde56e7acac
go: downloading github.com/go-chi/chi v4.1.2+incompatible
go: downloading github.com/lucas-clemente/quic-go v0.17.3
go: downloading github.com/smallstep/truststore v0.9.6
go: downloading github.com/smallstep/nosql v0.3.0
go: downloading github.com/marten-seemann/qpack v0.1.0
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/golang/protobuf v1.4.1
go: downloading github.com/cheekybits/genny v1.0.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/francoispqt/gojay v1.2.13
go: downloading github.com/dgraph-io/badger v1.5.3
go: downloading github.com/yuin/goldmark v1.2.1
go: downloading github.com/smallstep/cli v0.14.6
go: downloading github.com/marten-seemann/qtls v0.9.1
go: downloading github.com/dgraph-io/badger/v2 v2.0.1-rc1.0.20200413122845-09dd2e1a4195
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/Masterminds/sprig/v3 v3.1.0
go: downloading github.com/dgraph-io/ristretto v0.0.2-0.20200115201040-8f368f2f2ab3
go: downloading github.com/mitchellh/copystructure v1.0.0
go: downloading github.com/yuin/goldmark-highlighting v0.0.0-20200307114337-60d527fdb691
go: downloading github.com/naoina/toml v0.1.1
go: downloading github.com/alecthomas/chroma v0.8.0
go: downloading github.com/mitchellh/reflectwalk v1.0.0
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: downloading github.com/huandu/xstrings v1.3.1
go: downloading github.com/naoina/go-stringutil v0.1.0
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/dgryski/go-farm v0.0.0-20190423205320-6a90982ecee2
go: downloading github.com/google/uuid v1.1.1
go: downloading go.etcd.io/bbolt v1.3.2
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/manifoldco/promptui v0.3.1
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/dlclark/regexp2 v1.2.0
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/Masterminds/semver v1.4.2
go: downloading github.com/Masterminds/semver/v3 v3.1.0
go: downloading github.com/urfave/cli v1.22.2
go: downloading github.com/imdario/mergo v0.3.8
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/antlr/antlr4 v0.0.0-20200503195918-621b933c7a7f
go: downloading github.com/jsternberg/zap-logfmt v1.2.0
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/juju/ansiterm v0.0.0-20180109212912-720a0952cc2a
go: downloading github.com/mattn/go-colorable v0.1.6
go: downloading github.com/lunixbochs/vtclean v1.0.0
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/samfoo/ansi v0.0.0-20160124022901-b6bd2ded7189
go: downloading github.com/danwakefield/fnmatch v0.0.0-20160403171240-cbb64ac3d964
go: downloading github.com/Masterminds/goutils v1.1.0
go: downloading github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading cloud.google.com/go v0.54.0
go: downloading google.golang.org/grpc v1.27.1
go: downloading github.com/googleapis/gax-go v2.0.0+incompatible
go: downloading google.golang.org/api v0.20.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading go.opencensus.io v0.22.3
go: downloading github.com/google/go-cmp v0.5.0
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
# github.com/smallstep/certificates/authority/provisioner
/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/jwk.go:155:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/x5c.go:197:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
2020/08/08 15:22:32 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-08-08-1521.391743880
2020/08/08 15:22:32 [FATAL] exit status 2
```

Is it something that I am doing wrongly?

EDIT: I was able to build a Dockerfile using `caddy:builder` image. If anyone's interested: https://github.com/mr-karan/caddy-plugins-docker

**Comment by oxalorg** [comment]
I'm having the same issue.

I think it's linked with https://github.com/smallstep/certificates/issues/333

**Comment by oxalorg** [comment]
Looks like it was an issue with upstream. It's fixed in this commit https://github.com/caddyserver/caddy/commit/2a5599e2ad7f2d894915365782b3e4e1022c8e06

**Comment by symgryph** [comment]
Having same problem. Looks like the pinning to master fixes it.

**Comment by mholt** [comment]
You can pin to master for now, but safer might be a tagged release:

```
xcaddy build v2.2.0-rc.1 \
    --with github.com/caddy-dns/cloudflare@latest
```

Once v2.2.0 is tagged, you won't have to specify the version anymore.

**Comment by NetHeritage** [comment]
**INPUT:**  xcaddy build v2.1.1 --with github.com/caddy-dns/cloudflare@latest

**OUT:**2020/09/01 08:33:21 [INFO] Temporary folder: /tmp/buildenv_2020-09-01-0833.53261                                                                                                             1091
2020/09/01 08:33:21 [INFO] Writing main module: /tmp/buildenv_2020-09-01-0833.53                                                                                                             2611091/main.go
2020/09/01 08:33:21 [INFO] Initializing Go module
2020/09/01 08:33:21 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init cad                                                                                                             dy
go: creating new go.mod: module caddy
2020/09/01 08:33:21 [INFO] Pinning versions
2020/09/01 08:33:21 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v git                                                                                                             hub.com/caddyserver/caddy/v2@v2.1.1
2020/09/01 08:33:22 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v git                                                                                                             hub.com/caddy-dns/cloudflare@latest
go: github.com/caddy-dns/cloudflare latest => v0.0.0-20200811180534-4494da72fa56
2020/09/01 08:33:23 [INFO] Build environment ready
2020/09/01 08:33:23 [INFO] Building Caddy
2020/09/01 08:33:23 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /roo                                                                                                             t/caddy -ldflags -w -s -trimpath
# github.com/smallstep/certificates/authority/provisioner
/root/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953                                                                                                             -e855707dc274/authority/provisioner/jwk.go:155:24: assignment mismatch: 3 variab                                                                                                             les but x509util.SplitSANs returns 4 values
/root/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953                                                                                                             -e855707dc274/authority/provisioner/x5c.go:197:24: assignment mismatch: 3 variab                                                                                                             les but x509util.SplitSANs returns 4 values
2020/09/01 08:33:24 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-09-0                                                                                                             1-0833.532611091
2020/09/01 08:33:24 [FATAL] exit status 2






**INPUT**:xcaddy build v2.2.0-rc.1 --with github.com/caddy-dns/cloudflare@latest

**OUTPUT:**
2020/09/01 08:34:15 [INFO] Temporary folder: /tmp/buildenv_2020-09-01-0834.242359201
2020/09/01 08:34:15 [INFO] Writing main module: /tmp/buildenv_2020-09-01-0834.242359201/main.go
2020/09/01 08:34:15 [INFO] Initializing Go module
2020/09/01 08:34:15 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy
go: creating new go.mod: module caddy
2020/09/01 08:34:15 [INFO] Pinning versions
2020/09/01 08:34:15 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.2.0-rc.1
2020/09/01 08:34:19 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddy-dns/cloudflare@latest
go: github.com/caddy-dns/cloudflare latest => v0.0.0-20200811180534-4494da72fa56
2020/09/01 08:34:19 [INFO] Build environment ready
2020/09/01 08:34:19 [INFO] Building Caddy
2020/09/01 08:34:19 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /root/caddy -ldflags -w -s -trimpath
go: downloading github.com/smallstep/certificates v0.14.6
2020/09/01 08:34:38 [INFO] Build complete: caddy
2020/09/01 08:34:38 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-09-01-0834.242359201



**So, the real reason is cloudflare-dns plugin dose not support caddy 2.1.1???**

**Comment by mholt** [comment]
> So, the real reason is cloudflare-dns plugin dose not support caddy 2.1.1???

More or less; we're in the middle of transitioning to support Caddy 2.2, which uses a new ACME library I wrote called [acmez](https://github.com/mholt/acmez). It's a little awkward until the tags are made.

**Comment by danihodovic** [comment]
any update @mholt ?

**Comment by mholt** [comment]
@danihodovic On what?

**Comment by danihodovic** [comment]
Following the instructions on docker hub and using the cloudflare plugin:
```
/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/jwk.go:155:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/x5c.go:197:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
2020/11/21 19:39:48 [INFO] Skipping cleanup as requested; leaving folder intact: /tmp/buildenv_2020-11-21-1938.415922164
2020/11/21 19:39:48 [FATAL] exit status 2
The command '/bin/sh -c xcaddy build                            --with github.com/caddy-dns/cloudflare@latest' returned a non-zero code: 1

```

**Comment by mholt** [comment]
Works for me. Make sure your local system and environment are not caching anything old or doing anything weird/unusual. (I have a clean Linux install with Go 1.15.3.)

**Comment by danihodovic** [comment]
Works with caddy 2.2.1, but not 2.1.1. Thanks

**Comment by mholt** [comment]
I just copied and pasted your command you posted above, which uses the latest tagged version. If the last time you tried running that command was 2-3 months ago, that explains the issue.
