### ISSUE TITLE
Certificate for private ip

### ISSUE THREAD

**Issue by Tokariew** [caddy-dns/cloudflare#47]
Up to late september i was using cloudflare dns to get certifacte for my homelab on my local network, 192.168.0.xxx.
But now when caddy want to refresh certificate i get the following error.

In cloudflare dashboard i had setup 
A record for lab.example.com and ip to 192.168.0.113

```
{"level":"error","ts":1668018453.8717525,"logger":"tls.renew","msg":"could not get certificate from issuer","identifier":"lab.example.com","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:dns - no valid A records found for lab.example.com; no valid AAAA records found for lab.example.com"}
```

My Caddyfile
```
# vim: ft=caddyfile
(cloudflare) {
	tls cloudflare@tokariew.bulc.club {
        dns cloudflare (env.CLOUDFLARE_API_TOKEN)
        resolvers 1.1.1.1 1.0.0.1
	}
}

{env.DOMAIN} {
	import cloudflare
	encode zstd gzip
	handle_path /kosync/* {
		reverse_proxy kosync:8081
	}
	root * /srv/web
	handle {
		file_server {
			precompressed br zstd gzip
		}
	}
}

wallabag.{env.DOMAIN} {
	import cloudflare
	reverse_proxy wallabag:80
}
```

**Comment by mholt** [comment]
Let's Encrypt says that your domain doesn't have any valid A or AAAA records. Unfortunately you redacted your domain so I'm unable to help any further :(

**Comment by Tokariew** [comment]
my domain is lab.tokariew.xyz
and this is from my dashboard…
I was able to get the cert earlier with my setup.
![image](https://user-images.githubusercontent.com/7306237/200926079-bdb93d38-4a27-409b-9028-6ae803c27625.png)

**Comment by mholt** [comment]
Ok, that should probably work.

What changed from earlier to now?

**Comment by Tokariew** [comment]
Rebuild caddy podman/docker image.
Should i grab earlier release of docker image?

**Comment by mholt** [comment]
Can you provide more details?

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222) Please enable debug and access logs.
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by Tokariew** [comment]
i started to get working on it, but when I replaced variables in Caddyfile with my domain and api key, it started to work. 
So I messed up a Caddyfile syntax. Sorry for problem :(
