### ISSUE TITLE
Can modules be installed to an existing caddy installation?

### ISSUE THREAD

**Issue by umaar** [caddy-dns/cloudflare#67]
I didn't use xcaddy or caddyserver.com/download - wondering if there's an alternative technique to install this module?

**Comment by mholt** [comment]
You can use the caddy add-package command! I'm mobile but look it up and you'll find it 👍

**Comment by umaar** [comment]
Thanks! Oh didn't realise a package and module are the same. I tried `caddy add-package cloudflare` and `caddy add-package dns.providers.cloudflare` but just realised the docs show the proper command: `caddy add-package github.com/caddy-dns/cloudflare`!

**Comment by mholt** [comment]
Glad you got it.

Packages and modules are actually different.

A Go module can have multiple Go packages in it.

A Go package can have one or multiple Caddy modules in it.

So add package adds a whole package of modules because we can't actually choose which modules in a package to install, they self register.

**Comment by umaar** [comment]
Thank you! Great project btw. Was thinking of making a little video showing how easy it has been to host multiple web apps on a cheap VPS with Caddy, and how much cheaper it is compared to other services that charge per app/container.

**Comment by spielhoelle** [comment]
For everybody who comes here:
```
caddy add-package github.com/caddy-dns/cloudflare
```
Thats it
