### ISSUE TITLE
Request: Install instructions

### ISSUE THREAD

**Issue by douglasg14b** [caddy-dns/cloudflare#83]
Can this module include instructions on how to install or dd it to a new or existing caddy setup on common platform?

**Comment by devnoname120** [comment]
See: https://caddyserver.com/docs/modules/dns.providers.cloudflare

**Comment by mholt** [comment]
Caddy documentation explains how to add/remove plugins, either with `xcaddy` (linked above by @devnoname120  -- thanks!) or the CLI for existing binaries: https://caddyserver.com/docs/command-line#caddy-add-package

**Comment by devnoname120** [comment]
@mholt Is `caddy add-package` recommended even if `caddy` was installed from a Linux package manager?

**Comment by mholt** [comment]
Ironically, most (all?) Linux package managers unfortunately do not have the ability to manage packages for software like Caddy... they only support dynamically-linked builds not statically-linked builds. Which is bonkers to me, since anyone can dynamically link libs. It's the statically-linked builds that need to assist with compilation to make it easier.

Anyway, I digress... you can use `caddy add-package` but I presume that the next time your system package manager updates, it will wipe out the customizations.

**Comment by douglasg14b** [comment]
It's kind of awkward that the easiest way to find the instructions is to find issues.

The caddy docs are not really that discoverable, and its not obvious that every 3rd party project like this will be contained in their docs in the first place.

Which is why I made this issue, It should be in THIS projects readme.

At least there is now another issue people can search for to find hints at how to add this project

**Comment by mholt** [comment]
Sure, we can add a sentence that links to the Caddy docs for how to do this, for instance.

How about above the "Configuration" section (after "Module name") there's a new section for installing this plugin, with a couple different options (new build, existing build) -- and just link to the docs.
